sudo: required
dist: trusty

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools libqt5multimedia5 qtmultimedia5-dev libfftw3-3 libfftw3-dev libegl1-mesa

script:
  - cd sdcore
  - qmake sdcore.pro 
  - make
  - sudo cp -d build/libsdcore.so* /usr/lib/
  - cd ..
  - qmake SimDSP.pro
  - make
  - timeout 10 ./SimDSP
